export const mockProperties = [
  {
    id: 1,
    type: 'Apartment',
    location: '123 Main St, Downtown',
    price: 1200,
    priceUnit: 'month',
    bedrooms: 2,
    bathrooms: 1,
    description: 'Modern apartment with city views',
    images: [{ url: 'https://images.unsplash.com/photo-1522708323590-d24dbb6b0267?w=400&h=300&fit=crop', description: 'Apartment view' }],
    rating: 4.5,
    tenant: 'John Doe',
    leaseEnd: '2024-12-15',
    leaseStart: '2024-01-15',
    tenantPhone: '+1 (555) 123-4567',
    tenantEmail: 'john.doe@email.com',
    squareFootage: 850,
    furnished: true,
    petFriendly: false,
    amenities: ['Air Conditioning', 'Dishwasher', 'Laundry in Unit', 'Parking Space']
  },
  {
    id: 2,
    type: 'House',
    location: '456 Oak Ave, Suburbs',
    price: 2500,
    priceUnit: 'month',
    bedrooms: 3,
    bathrooms: 2,
    description: 'Spacious family home with garden',
    images: [{ url: 'https://images.unsplash.com/photo-1570129477492-45c003edd2be?w=400&h=300&fit=crop', description: 'House exterior' }],
    rating: 4.8,
    tenant: null,
    leaseEnd: null,
    leaseStart: null,
    tenantPhone: null,
    tenantEmail: null,
    squareFootage: 1800,
    furnished: false,
    petFriendly: true,
    amenities: ['Garden', 'Garage', 'Fireplace', 'Central Heating']
  },
  {
    id: 3,
    type: 'Condo',
    location: '789 Pine St, Midtown',
    price: 1800,
    priceUnit: 'month',
    bedrooms: 1,
    bathrooms: 1,
    description: 'Luxury condo with amenities',
    images: [{ url: 'https://images.unsplash.com/photo-1545324418-cc1a3fa10c00?w=400&h=300&fit=crop', description: 'Condo interior' }],
    rating: 4.2,
    tenant: 'Jane Smith',
    leaseEnd: '2024-08-30',
    leaseStart: '2023-08-30',
    tenantPhone: '+1 (555) 987-6543',
    tenantEmail: 'jane.smith@email.com',
    squareFootage: 750,
    furnished: true,
    petFriendly: true,
    amenities: ['Gym', 'Pool', 'Concierge', 'Rooftop Terrace']
  }
];